name: "HomeGlo"
description: "Right light, right time"
version: "1.0.67"
slug: "homeglo"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
ingress_port: 80
panel_icon: mdi:lightbulb
map:
  - data:rw
homeassistant_api: true
auth_api: true