<?php

use yii\db\Migration;

/**
 * Class m220920_141303_action_data
 */
class m220920_141303_action_data extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

        $this->execute("INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (10, null, null, null, 'midday', 'Mid Day', 'Mid Day', 100, 1, null, 1, null, 1, 0.3143, 0.3301, 254, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (20, null, null, null, 'day', 'Day', 'Day', 100, 1, null, 1, null, 2, 0.3669, 0.3706, 254, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (30, null, null, null, 'golden_hour', 'Golden Hour', 'Golden Hour', 100, 1, null, 1, null, 3, 0.4041, 0.3881, 254, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (40, null, null, null, 'gloaming', 'Gloaming', 'Gloaming', 100, 1, null, 1, null, 4, 0.4412, 0.4055, 212, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (50, null, null, null, 'unwind', 'Unwind', 'Unwind', 100, 1, null, 1, null, 5, 0.4824, 0.4142, 128, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (60, null, null, null, 'mellow', 'Mellow', 'Mellow', 100, 1, null, 1, null, 6, 0.5213, 0.4139, 102, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (70, null, null, null, 'mellowtonin', 'MellowTonin', 'MellowTonin', 100, 1, null, 1, null, 7, 0.6092, 0.3701, 62, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (80, null, null, null, 'nitelite', 'NiteLite', 'NiteLite', 100, 1, null, 1, null, 8, 0.6092, 0.3701, 10, null);
INSERT INTO hg_glo (id, created_at, updated_at, base_hg_glo_id, name, hub_name, display_name, hg_status_id, hg_glozone_id, hg_hub_id, hg_version_id, hue_ids, `rank`, hue_x, hue_y, brightness, metadata) VALUES (90, null, null, null, 'bright', 'Bright', 'Bright', 100, 1, null, 1, null, 9, 0.3669, 0.3706, 254, null);
");

        $string = <<<EOD
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (10, 'midnight', 'Midnight', 1, 70, 400, null, '((bed_time))+90', '((bed_time))+180', 'inactive', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (20, 'early_morning', 'Early Morning', 1, 80, 400, null, '((bed_time))+180', '((wake_time))+0', 'active', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (21, 'dawn', 'Dawn', 1, 40, 400, null, '((wake_time))+0', '((sunrise))+0', 'inactive', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (22, 'sunrise', 'Sunrise', 1, 30, 400, null, '((sunrise))+0', '((sunrise))+15', 'inactive', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (30, 'morning', 'Morning', 1, 20, 400, null, '((sunrise))+15', '((sunrise))+180', 'inactive', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (40, 'day', 'Day', 1, 10, 400, null, '((sunrise))+180', '((sunset))-180', 'inactive', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (50, 'afternoon', 'Afternoon', 1, 20, 400, null, '((sunset))-180', '((sunset))-15', 'active', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (60, 'sunset', 'Sunset', 1, 30, 400, null, '((sunset))-15', '((sunset))+0', 'inactive', 'inactive', 'in_cycle_on', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (70, 'dusk', 'Dusk', 1, 40, 400, null, '((sunset))+0', '((bed_time))-90', 'active', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (80, 'evening', 'Evening', 1, 50, 400, null, '((bed_time))-90', '((bed_time))+0', 'active', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);
INSERT INTO hg_glozone_time_block (id, name, display_name, hg_glozone_id, default_hg_glo_id, hg_status_id, base_hg_glozone_time_block_id, time_start_default_midnightmins, time_end_default_midnightmins, smartOn_switch_behavior, smartOn_motion_behavior, smartTransition_behavior, smartTransition_duration_ms, time_start_sun_midnightmins, time_end_sun_midnightmins, time_start_mon_midnightmins, time_end_mon_midnightmins, time_start_tue_midnightmins, time_end_tue_midnightmins, time_start_wed_midnightmins, time_end_wed_midnightmins, time_start_thu_midnightmins, time_end_thu_midnightmins, time_start_fri_midnightmins, time_end_fri_midnightmins, time_start_sat_midnightmins, time_end_sat_midnightmins, timezone, metadata) VALUES (90, 'late_evening', 'Late Evening', 1, 60, 400, null, '((bed_time))+0', '((bed_time))+90', 'active', 'inactive', 'inactive', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'America/New_York', null);

EOD;

        $this->execute($string);

        $this->execute("INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (21, null, null, null, 1, 300, 'hue_dimmer_switch', 'smartOff_shortPress', 'Smart Off', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (20, null, null, null, 1, 300, 'hue_dimmer_switch', 'smartOn_shortPress', 'Smart On', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (7, null, null, null, 1, 300, 'hue_dimmer_switch', 'longpress_bottom_nitelite_button', 'Long Press Bottom -> Nitelite', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (6, null, null, null, 1, 300, 'hue_dimmer_switch', 'longpress_brighter_midday_button', 'Long Press Brighter -> Midday Scene', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (5, null, null, null, 1, 300, 'hue_dimmer_switch', 'longpress_top_brighter_button', 'Long Press Top -> Brighter Scene', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (4, null, null, null, 1, 300, 'hue_dimmer_switch', 'dimmer', 'Dimmer', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (3, null, null, null, 1, 300, 'hue_dimmer_switch', 'brighter', 'Brighter', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (2, null, null, null, 1, 300, 'hue_dimmer_switch', 'cycle_4_scenes', 'Cycle 4 Scenes', 'hue', null, null);
INSERT INTO hg_hub_action_template (id, created_at, updated_at, hg_hub_id, hg_version_id, hg_status_id, hg_product_sensor_type_name, name, display_name, platform, multi_room, metadata) VALUES (1, null, null, null, 1, 305, 'hue_dimmer_switch', 'smartOn_switch_5', 'Smart On 5', 'hue', null, null);
");

        $string = <<<EOD
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (197, null, null, '10_seconds_elapsed', '10 Seconds Elapsed', 'time', 'time_elapsed', null, null, null, 2, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (196, null, null, 'short_press_bottom_cycle_4', 'Short Press Bottom Cycle 4', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "4002"}', null, null, 2, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (195, null, null, 'short_press_bottom_cycle_3', 'Short Press Bottom Cycle 3', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "4002"}', null, null, 2, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (194, null, null, 'short_press_bottom_cycle_2', 'Short Press Bottom Cycle 2', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "4002"}', null, null, 2, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (193, null, null, 'short_press_bottom_cycle_1', 'Short Press Bottom Cycle 1', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "4002"}', null, null, 2, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (51, null, null, 'smartOff_short_press_top', 'Short Press Top Turn Off', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 21, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (50, null, null, 'smartOn_short_press_top', 'Short Press Top Turn On', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 20, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (12, null, null, 'short_press_top_turn_off', 'Short Press Top Turn Off', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 1, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (11, null, null, 'short_press_brighter', 'Short Press Brighter', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "2002"}', null, null, 3, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (10, null, null, 'short_press_top_time_5', 'Short Press Top Time 5', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 1, null, null, 90, 90, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (9, null, null, 'short_press_top_time_4', 'Short Press Top Time 4', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 1, null, null, 80, 80, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (8, null, null, 'long_press_bottom', 'Long Press Bottom', 'sensor', 'long_press', '{"\{\{hue_switch_button_id\}\}": "4001"}', null, null, 7, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (7, null, null, 'long_press_brighter', 'Long Press Brighter', 'sensor', 'long_press', '{"\{\{hue_switch_button_id\}\}": "2001"}', null, null, 6, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (6, null, null, 'long_press_top', 'Long Press Top', 'sensor', 'long_press', '{"\{\{hue_switch_button_id\}\}": "1001"}', null, null, 5, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (5, null, null, 'short_press_dimmer', 'Short Press Dimmer', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "3002"}', null, null, 4, null, null, null, null, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (3, null, null, 'short_press_top_time_3', 'Short Press Top Time 3', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 1, null, null, 60, 70, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (2, null, null, 'short_press_top_time_2', 'Short Press Top Time 2', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 1, null, null, 21, 50, 300, null, null);
INSERT INTO hg_hub_action_trigger (id, created_at, updated_at, name, display_name, source_name, event_name, event_data, last_triggered_at, last_checked_at, hg_hub_action_template_id, hg_hub_id, hg_device_sensor_id, hg_glozone_start_time_block_id, hg_glozone_end_time_block_id, hg_status_id, `rank`, metadata) VALUES (1, null, null, 'short_press_top_time_1', 'Short Press Top Time 1', 'sensor', 'short_press', '{"\{\{hue_switch_button_id\}\}": "1002"}', null, null, 1, null, null, 10, 20, 300, null, null);
EOD;
        $this->execute($string);

        $string = <<<EOD
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (7, null, null, 1, 300, 'rule_timeblock', 'Rule Time Block', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (8, null, null, 1, 300, 'rule_anyone', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (9, null, null, 1, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (6, null, null, 1, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (32, null, null, 2, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (31, null, null, 2, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (30, null, null, 2, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (29, null, null, 2, 300, 'rule_timeblock', 'Rule Time Block', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (35, null, null, 3, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (34, null, null, 3, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (33, null, null, 3, 300, 'rule_timeblock', 'Rule Time Block', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (36, null, null, 3, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (13, null, null, 5, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (12, null, null, 5, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (15, null, null, 6, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (14, null, null, 6, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (17, null, null, 7, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (16, null, null, 7, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (19, null, null, 8, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (18, null, null, 8, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (40, null, null, 9, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (38, null, null, 9, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (37, null, null, 9, 300, 'rule_timeblock', 'Rule Time Block', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (39, null, null, 9, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (41, null, null, 10, 300, 'rule_timeblock', 'Rule Time Block', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (42, null, null, 10, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (43, null, null, 10, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (44, null, null, 10, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (21, null, null, 11, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (20, null, null, 11, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (5206, null, null, 12, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (5207, null, null, 12, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (5208, null, null, 12, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'true', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (62, null, null, 50, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (64, null, null, 50, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (11180, null, null, 50, 300, 'rule_timeblock', 'Rule Time Block', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (11181, null, null, 50, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (11179, null, null, 51, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (11712, null, null, 51, 300, 'rule_anyon', 'Rule Any lights on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'true', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (63, null, null, 51, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (27, null, null, 193, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (26, null, null, 193, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (28, null, null, 193, 300, 'rule_sensor_state', 'Rule Sensor State', '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state/status', 'eq', '0', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (48, null, null, 194, 300, 'rule_sensor_state', 'Rule Sensor State', '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state/status', 'eq', '1', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (47, null, null, 194, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (46, null, null, 194, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (54, null, null, 195, 300, 'rule_sensor_state', 'Rule Sensor State', '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state/status', 'eq', '2', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (53, null, null, 195, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (49, null, null, 195, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (55, null, null, 196, 300, 'rule_buttonevent', 'Rule Button Event', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/buttonevent', 'eq', '\{\{hue_switch_button_id\}\}', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (56, null, null, 196, 300, 'rule_sensor_state', 'Rule Sensor State', '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state/status', 'gt', '2', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (57, null, null, 196, 300, 'rule_sensor_state', 'Rule Sensor State', '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state/status', 'lt', '1000', null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (52, null, null, 196, 300, 'rule_lastupdated', 'Rule Lastupdated', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/lastupdated', 'dx', null, null);
INSERT INTO hg_hub_action_condition (id, created_at, updated_at, hg_hub_action_trigger_id, hg_status_id, name, display_name, property, operator, value, metadata) VALUES (45, null, null, 197, 300, 'rule_time_elapsed', 'Rule Time Elapsed', '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state/lastupdated', 'ddx', 'PT00:00:10', null);

EOD;

        $this->execute($string);

        $string = <<<EOD
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (4, null, null, 1, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 80, 'Smart on Scene 1', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (10, null, null, 2, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 20, 'Smart on Scene 2', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (11, null, null, 3, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 40, 'Smart on Scene 3', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (6, null, null, 5, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'adjust_brightness', null, null, null, 'Dimmer', null, null, null, -17, 1, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (7, null, null, 6, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 90, 'Turn On Bright Scene', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (8, null, null, 7, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 10, 'Turn On Midday Scene', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (9, null, null, 8, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 80, 'Turn On Nitelite Scene', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (12, null, null, 9, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 50, 'Smart on Scene 4', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (13, null, null, 10, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 60, 'Smart on Scene 5', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (14, null, null, 11, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'adjust_brightness', null, null, null, 'Brighter', null, null, null, 17, 1, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (2679, null, null, 12, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 0}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (23, null, null, 12, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_off_room', null, null, null, 'Turn Off Room', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (100, null, null, 50, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, null, 'Smart on Scene', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (31, null, null, 51, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 0}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (32, null, null, 51, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_off_room', null, null, null, 'Turn Off Room', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (16, null, null, 193, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 1}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (15, null, null, 193, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 70, 'Cycle on MellowTonin', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (18, null, null, 194, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 60, 'Cycle on Mellow', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (21, null, null, 194, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 2}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (19, null, null, 195, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 50, 'Cycle on Unwind', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (22, null, null, 195, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 3}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (20, null, null, 196, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', null, null, 40, 'Cycle on Gloaming', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (2358, null, null, 196, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 0}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);
INSERT INTO hg_hub_action_item (id, created_at, updated_at, hg_hub_action_trigger_id, entity, operation_name, operation_value_json, operate_hg_device_light_group_id, hg_glo_id, display_name, override_hue_x, override_hue_y, override_bri_absolute, override_bri_increment_percent, override_transition_duration_ms, override_transition_at_time, metadata) VALUES (17, null, null, 197, '/sensors/\{\{hg_device_sensor.hue_sensor_variable_id\}\}/state', 'set_sensor_state', '{"status": 0}', null, null, 'Set Sensor State', null, null, null, null, null, null, null);

EOD;

        $this->execute($string);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m220920_141303_action_data cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m220920_141303_action_data cannot be reverted.\n";

        return false;
    }
    */
}
