<?php

use yii\db\Migration;

/**
 * Class m230124_172820_dual_motion_single_room_map
 */
class m230124_172820_dual_motion_single_room_map extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $str = <<<EOD
INSERT INTO `hg_hub_action_map` (`id`, `created_at`, `updated_at`, `hg_home_id`, `name`, `display_name`, `map_image_url`, `base_hg_hub_action_map_id`, `hg_product_sensor_map_type`, `hg_status_id`, `preserve_hue_buttons`, `metadata`) VALUES (20, 1674230073, 1674247801, NULL, 'motion_map_default', 'Two Motion Same Variable', '', NULL, 'hue_motion_sensor', NULL, CAST('\"\"' AS JSON), NULL);
INSERT INTO `hg_hub_action_template` (`id`, `created_at`, `updated_at`, `hg_hub_id`, `hg_version_id`, `hg_hub_action_map_id`, `hg_status_id`, `hg_product_sensor_type_name`, `name`, `display_name`, `platform`, `multi_room`, `metadata`) VALUES (988, 1674230073, 1674230073, NULL, 1, 20, 300, 'hue_motion_sensor', 'smartOn_motion', 'Smart On', 'hue', NULL, NULL);
INSERT INTO `hg_hub_action_trigger` (`id`, `created_at`, `updated_at`, `name`, `display_name`, `source_name`, `event_name`, `event_data`, `last_triggered_at`, `last_checked_at`, `hg_hub_action_template_id`, `hg_hub_id`, `hue_id`, `hg_device_sensor_id`, `hg_glozone_start_time_block_id`, `hg_glozone_end_time_block_id`, `hg_status_id`, `rank`, `metadata`) VALUES (2482, 1674230073, 1674230073, 'smartOn_short_press_top', 'Presence Turn On', 'sensor', 'presence', NULL, NULL, NULL, 988, NULL, NULL, NULL, NULL, NULL, 300, NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20481, 1674230073, 1674230073, 2482, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'eq', 'true', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20482, 1674230073, 1674230073, 2482, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'dx', NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20483, 1674230073, 1674230073, 2482, 300, 'condition_localtime', 'Condition localtime', '/config/localtime', 'in', '\{\{hgGlozoneTimeBlockStartTime\}\}/\{\{hgGlozoneTimeBlockEndTime\}\}', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20484, 1674230073, 1674230073, 2482, 300, 'condition_any_on', 'Condition any_on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20485, 1674230073, 1674230073, 2482, 300, 'condition_dark', 'Condition dark', '/sensors/\{\{hg_device_sensor.hue_ambient_sensor_id\}\}/state/dark', 'eq', 'true', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20486, 1674230073, 1674232495, 2482, NULL, 'condition_status', 'Condition status', '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state/status', 'lt', '1', NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6149, 1674230073, 1674232504, 2482, '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state', 'set_sensor_state', CAST('{\"status\":1}' AS JSON), NULL, NULL, 'Set Sensor State', NULL, NULL, NULL, '', '', NULL, NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6150, 1674230073, 1674230073, 2482, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_on_scene', NULL, NULL, NULL, 'Turn On Scene', NULL, NULL, NULL, NULL, '200', NULL, NULL);
INSERT INTO `hg_hub_action_template` (`id`, `created_at`, `updated_at`, `hg_hub_id`, `hg_version_id`, `hg_hub_action_map_id`, `hg_status_id`, `hg_product_sensor_type_name`, `name`, `display_name`, `platform`, `multi_room`, `metadata`) VALUES (989, 1674230073, 1674230073, NULL, 1, 20, 300, 'hue_motion_sensor', 'smartOff_finalize', 'Smart Off (Finalize)', 'hue', NULL, NULL);
INSERT INTO `hg_hub_action_trigger` (`id`, `created_at`, `updated_at`, `name`, `display_name`, `source_name`, `event_name`, `event_data`, `last_triggered_at`, `last_checked_at`, `hg_hub_action_template_id`, `hg_hub_id`, `hue_id`, `hg_device_sensor_id`, `hg_glozone_start_time_block_id`, `hg_glozone_end_time_block_id`, `hg_status_id`, `rank`, `metadata`) VALUES (2483, 1674230073, 1674230073, 'smartOff_finalize', 'Smart Off Finalize', 'sensor', 'smart_off', NULL, NULL, NULL, 989, NULL, NULL, NULL, NULL, NULL, 300, NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20487, 1674230073, 1674230073, 2483, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'eq', 'false', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20488, 1674230073, 1674232428, 2483, 300, 'condition_status', 'Condition status', '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state/status', 'ddx', '\{\{motion_finalize_timer\}\}', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20489, 1674230073, 1674232435, 2483, 300, 'condition_status', 'Condition status', '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state/status', 'gt', '1', NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6151, 1674230073, 1674230073, 2483, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'turn_off_room', NULL, NULL, NULL, 'Turn Off Room', NULL, NULL, NULL, NULL, 400, NULL, NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6152, 1674230073, 1674232451, 2483, '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state', 'set_sensor_state', CAST('{\"status\":0}' AS JSON), NULL, NULL, 'Set Sensor State', NULL, NULL, NULL, '', '', NULL, NULL);
INSERT INTO `hg_hub_action_template` (`id`, `created_at`, `updated_at`, `hg_hub_id`, `hg_version_id`, `hg_hub_action_map_id`, `hg_status_id`, `hg_product_sensor_type_name`, `name`, `display_name`, `platform`, `multi_room`, `metadata`) VALUES (990, 1674230073, 1674230073, NULL, 1, 20, 300, 'hue_motion_sensor', 'smart_dim_restore', 'Smart Dim (Restore)', 'hue', NULL, NULL);
INSERT INTO `hg_hub_action_trigger` (`id`, `created_at`, `updated_at`, `name`, `display_name`, `source_name`, `event_name`, `event_data`, `last_triggered_at`, `last_checked_at`, `hg_hub_action_template_id`, `hg_hub_id`, `hue_id`, `hg_device_sensor_id`, `hg_glozone_start_time_block_id`, `hg_glozone_end_time_block_id`, `hg_status_id`, `rank`, `metadata`) VALUES (2484, 1674230073, 1674230073, 'smart_dim_restore', 'Smart Dim Restore', 'sensor', 'smart_dim_restore', NULL, NULL, NULL, 990, NULL, NULL, NULL, NULL, NULL, 300, NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20490, 1674230073, 1674230073, 2484, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'eq', 'true', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20491, 1674230073, 1674230073, 2484, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'dx', NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20492, 1674230073, 1674232354, 2484, 300, 'condition_status', 'Condition status', '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state/status', 'gt', '1', NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6153, 1674230073, 1674232367, 2484, '/groups/0/action', 'turn_on_temp_deviceGroup_scene', NULL, NULL, NULL, 'Turn On Temp DeviceGroup Scene', NULL, NULL, NULL, '', '200', NULL, NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6154, 1674230073, 1674232387, 2484, '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state', 'set_sensor_state', CAST('{\"status\":1}' AS JSON), NULL, NULL, 'Set Sensor State', NULL, NULL, NULL, '', '', NULL, NULL);
INSERT INTO `hg_hub_action_template` (`id`, `created_at`, `updated_at`, `hg_hub_id`, `hg_version_id`, `hg_hub_action_map_id`, `hg_status_id`, `hg_product_sensor_type_name`, `name`, `display_name`, `platform`, `multi_room`, `metadata`) VALUES (991, 1674230073, 1674230073, NULL, 1, 20, 300, 'hue_motion_sensor', 'arm', 'Arm', 'hue', NULL, NULL);
INSERT INTO `hg_hub_action_trigger` (`id`, `created_at`, `updated_at`, `name`, `display_name`, `source_name`, `event_name`, `event_data`, `last_triggered_at`, `last_checked_at`, `hg_hub_action_template_id`, `hg_hub_id`, `hue_id`, `hg_device_sensor_id`, `hg_glozone_start_time_block_id`, `hg_glozone_end_time_block_id`, `hg_status_id`, `rank`, `metadata`) VALUES (2485, 1674230073, 1674230073, 'smart_motion_arm', 'Arm', 'sensor', 'arm', NULL, NULL, NULL, 991, NULL, NULL, NULL, NULL, NULL, 300, NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20493, 1674230073, 1674230073, 2485, 300, 'condition_any_on', 'Condition any_on', '/groups/\{\{hg_device_group[0].hue_id\}\}/state/any_on', 'eq', 'false', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20494, 1674230073, 1674230073, 2485, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'eq', 'false', NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6155, 1674230073, 1674513913, 2485, '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state', 'set_sensor_state', CAST('{\"status\":0}' AS JSON), NULL, NULL, 'Set Sensor State', NULL, NULL, NULL, '', '', NULL, NULL);
INSERT INTO `hg_hub_action_template` (`id`, `created_at`, `updated_at`, `hg_hub_id`, `hg_version_id`, `hg_hub_action_map_id`, `hg_status_id`, `hg_product_sensor_type_name`, `name`, `display_name`, `platform`, `multi_room`, `metadata`) VALUES (992, 1674230073, 1674230073, NULL, 1, 20, 300, 'hue_motion_sensor', 'smart_dim_halfway', 'Smart Dim (Halfway)', 'hue', NULL, NULL);
INSERT INTO `hg_hub_action_trigger` (`id`, `created_at`, `updated_at`, `name`, `display_name`, `source_name`, `event_name`, `event_data`, `last_triggered_at`, `last_checked_at`, `hg_hub_action_template_id`, `hg_hub_id`, `hue_id`, `hg_device_sensor_id`, `hg_glozone_start_time_block_id`, `hg_glozone_end_time_block_id`, `hg_status_id`, `rank`, `metadata`) VALUES (2486, 1674230073, 1674230073, 'short_press_dimmer', 'Presence Dim (Halfway)', 'sensor', 'half_time_passed', NULL, NULL, NULL, 992, NULL, NULL, NULL, NULL, NULL, 300, NULL, NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20495, 1674230073, 1674230073, 2486, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'eq', 'false', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20496, 1674230073, 1674230073, 2486, 300, 'condition_presence', 'Condition presence', '/sensors/\{\{hg_device_sensor.hue_id\}\}/state/presence', 'ddx', '\{\{motion_warning_timer\}\}', NULL);
INSERT INTO `hg_hub_action_condition` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `hg_status_id`, `name`, `display_name`, `property`, `operator`, `value`, `metadata`) VALUES (20497, 1674230073, 1674232308, 2486, NULL, 'condition_status', 'Condition status', '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state/status', 'eq', '1', NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6156, 1674230074, 1674249140, 2486, '/scenes/\{\{hg_device_group.hue_motion_scene_id\}\}', 'storelightstate_deviceGroup', NULL, NULL, NULL, 'Storelightstate DeviceGroup', NULL, NULL, NULL, '', '', NULL, NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6157, 1674230074, 1674232333, 2486, '/sensors/\{\{hg_device_group.hue_motion_variable_id\}\}/state', 'set_sensor_state', CAST('{\"status\":2}' AS JSON), NULL, NULL, 'Set Sensor State', NULL, NULL, NULL, '', '', NULL, NULL);
INSERT INTO `hg_hub_action_item` (`id`, `created_at`, `updated_at`, `hg_hub_action_trigger_id`, `entity`, `operation_name`, `operation_value_json`, `operate_hg_device_light_group_id`, `hg_glo_id`, `display_name`, `override_hue_x`, `override_hue_y`, `override_bri_absolute`, `override_bri_increment_percent`, `override_transition_duration_ms`, `override_transition_at_time`, `metadata`) VALUES (6158, 1674230074, 1674230074, 2486, '/groups/\{\{hg_device_group.hue_id\}\}/action', 'adjust_brightness', NULL, NULL, NULL, 'Adjust Brightness', NULL, NULL, NULL, '-50', NULL, NULL, NULL);
EOD;

        $this->execute($str);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->delete('hg_hub_action_map',['id'=>20]);

        return true;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m230124_172820_dual_motion_single_room_map cannot be reverted.\n";

        return false;
    }
    */
}
